development:
  secret_key_base: <%= ENV['RAILS_SECRET_TOKEN'] %>
  smtp_server: <%= ENV['SMTP_SERVER'] %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_override_recipient: <%= ENV['SMTP_OVERRIDE_RECIPIENT'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  google_analytics_account: <%= ENV['GOOGLE_ANALYTICS_ACCOUNT'] %>
  staff_email: <%= ENV['STAFF_NOTIFICATION_EMAIL'] %>
  canvas_access_token: <%= ENV['CANVAS_ACCESS_TOKEN'] %>
  canvas_server: <%= ENV['CANVAS_SERVER'] %>
  canvas_port: <%= ENV['CANVAS_PORT'] %>
  canvas_use_ssl: <%= ENV['CANVAS_USE_SSL'] %>
  canvas_allow_self_signed_ssl: <%= ENV['CANVAS_ALLOW_SELF_SIGNED_SSL'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  blog_url: <%= ENV['BLOG_URL'] %>
  salesforce_host: <%= ENV['SALESFORCE_HOST'] %>
  salesforce_username: <%= ENV['SALESFORCE_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_SECURITY_TOKEN'] %>
  default_lead_owner: <%= ENV['DEFAULT_LEAD_OWNER'] %>
  salesforce_magic_token: <%= ENV['SALESFORCE_MAGIC_TOKEN'] %>

test:
  # The secret key for test can be anything, since it isn't actually
  # running anywhere in public, it is impossible to exploit.
  # I hardcode it here to avoid the necessity of setting up a .env
  # file on Travis via github commits which would likely conflict with
  # our local dev environments (the file would be liable to be overwritten
  # when we do a git pull and that would be annoying)
  secret_key_base: '1242367676'
  smtp_server: <%= ENV['SMTP_SERVER'] %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  # No emails are actually sent from the test server, but
  # it does need a to email lest it throws "invalid smtp email" exceptions
  smtp_override_recipient: destructionator+beyondztest@gmail.com
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  devise_pepper: '12312321322'
  devise_secret_key: '12312312312'
  google_analytics_account: <%= ENV['GOOGLE_ANALYTICS_ACCOUNT'] %>
  staff_email: <%= ENV['STAFF_NOTIFICATION_EMAIL'] %>
  canvas_access_token: <%= ENV['CANVAS_ACCESS_TOKEN'] %>
  canvas_server: <%= ENV['CANVAS_SERVER'] %>
  canvas_port: <%= ENV['CANVAS_PORT'] %>
  canvas_use_ssl: <%= ENV['CANVAS_USE_SSL'] %>
  canvas_allow_self_signed_ssl: <%= ENV['CANVAS_ALLOW_SELF_SIGNED_SSL'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  blog_url: <%= ENV['BLOG_URL'] %>
  salesforce_host: <%= ENV['SALESFORCE_HOST'] %>
  salesforce_username: <%= ENV['SALESFORCE_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_SECURITY_TOKEN'] %>
  default_lead_owner: <%= ENV['DEFAULT_LEAD_OWNER'] %>
  salesforce_magic_token: <%= ENV['SALESFORCE_MAGIC_TOKEN'] %>

staging:
  secret_key_base: <%= ENV['RAILS_SECRET_TOKEN'] %>
  smtp_server: <%= ENV['SMTP_SERVER'] %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_override_recipient: <%= ENV['SMTP_OVERRIDE_RECIPIENT'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  google_analytics_account: <%= ENV['GOOGLE_ANALYTICS_ACCOUNT'] %>
  staff_email: <%= ENV['STAFF_NOTIFICATION_EMAIL'] %>
  canvas_access_token: <%= ENV['CANVAS_ACCESS_TOKEN'] %>
  canvas_server: <%= ENV['CANVAS_SERVER'] %>
  canvas_port: <%= ENV['CANVAS_PORT'] %>
  canvas_use_ssl: <%= ENV['CANVAS_USE_SSL'] %>
  canvas_allow_self_signed_ssl: <%= ENV['CANVAS_ALLOW_SELF_SIGNED_SSL'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  blog_url: <%= ENV['BLOG_URL'] %>
  salesforce_host: <%= ENV['SALESFORCE_HOST'] %>
  salesforce_username: <%= ENV['SALESFORCE_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_SECURITY_TOKEN'] %>
  default_lead_owner: <%= ENV['DEFAULT_LEAD_OWNER'] %>
  salesforce_magic_token: <%= ENV['SALESFORCE_MAGIC_TOKEN'] %>

production:
  secret_key_base: <%= ENV['RAILS_SECRET_TOKEN'] %>
  smtp_server: <%= ENV['SMTP_SERVER'] %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  devise_pepper: <%= ENV['DEVISE_PEPPER'] %>
  devise_secret_key: <%= ENV['DEVISE_SECRET_KEY'] %>
  google_analytics_account: <%= ENV['GOOGLE_ANALYTICS_ACCOUNT'] %>
  staff_email: <%= ENV['STAFF_NOTIFICATION_EMAIL'] %>
  canvas_access_token: <%= ENV['CANVAS_ACCESS_TOKEN'] %>
  canvas_server: <%= ENV['CANVAS_SERVER'] %>
  canvas_port: <%= ENV['CANVAS_PORT'] %>
  canvas_use_ssl: <%= ENV['CANVAS_USE_SSL'] %>
  canvas_allow_self_signed_ssl: <%= ENV['CANVAS_ALLOW_SELF_SIGNED_SSL'] %>
  sso_url: <%= ENV['SSO_URL'] %>
  blog_url: <%= ENV['BLOG_URL'] %>
  # Note: the database dot com env vars are NOT here because
  # they are managed automatically by the gem - the environment variable
  # needs to be present, but we don't explicitly use it in our code
  salesforce_host: <%= ENV['SALESFORCE_HOST'] %>
  salesforce_username: <%= ENV['SALESFORCE_USERNAME'] %>
  salesforce_password: <%= ENV['SALESFORCE_PASSWORD'] %>
  salesforce_security_token: <%= ENV['SALESFORCE_SECURITY_TOKEN'] %>
  default_lead_owner: <%= ENV['DEFAULT_LEAD_OWNER'] %>
  salesforce_magic_token: <%= ENV['SALESFORCE_MAGIC_TOKEN'] %>
